---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app language-tools
  namespace: services
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: silviof/docker-languagetool
      tag: latest@sha256:8869bd7de7f28e69e06a6d4221618302f5bc1ef4ab990fe907b0fb0880bcd4f4
    service:
      main:
        ports:
          http:
            port: 8010
    ingress:
      main:
        enabled: true
        ingressClassName: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.${EXTERNAL_DOMAIN}
          hajimari.io/enable: "false"
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 15m
        memory: 716M
      limits:
        memory: 1307M
