{
 "title": "DockerShit",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Dockerhub Containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(time() - container_last_seen{image=~\"(docker.io).*\",container!=\"\"} < 30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique Dockerhub Containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (image) (time() - container_last_seen{image=~\"(docker.io).*\",container!=\"\"} < 30))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Containers",
   "type": "table",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "time() - container_last_seen{image=~\"(docker.io).*\",container!=\"\"} < 30",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}