---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app multi-scrobbler
  namespace: services
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false

        containers:
          main:
            image:
              repository: ghcr.io/foxxmd/multi-scrobbler
              tag: 0.7.0@sha256:dd94fd15aa6c1fd55b91ea6b483b9dd73c7cb6be120344c7e4b5dd967d1d6b96

            # resources:
            #   requests:
            #     cpu: 10m
            #     memory: 128Mi
            #   limits:
            #     memory: 512Mi

    service:
      main:
        ports:
          http:
            port: 9078

    ingress:
      main:
        enabled: true
        className: "internal-nginx"
        hosts:
          - host: &host "{{ .Release.Name }}.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: multi-scrobbler-config-v1
      config-file:
        type: secret
        name: multi-scrobbler
        globalMounts:
          - path: /config/config.json
            subPath: config.json
            readOnly: true
